"""Add location photos

Revision ID: 0b77cfadde45
Revises: a01bf8ab170d
Create Date: 2018-05-01 03:36:47.175249

"""
from alembic import op
import sqlalchemy as sa
import hapcat.types
import sqlalchemy_utils.types


# revision identifiers, used by Alembic.
revision = '0b77cfadde45'
down_revision = 'a01bf8ab170d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_photo',
    sa.Column('location_id', sqlalchemy_utils.types.uuid.UUIDType, nullable=False),
    sa.Column('photo_id', sqlalchemy_utils.types.uuid.UUIDType, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk-location_photo-location_id-location-id'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], name=op.f('fk-location_photo-photo_id-photo-id'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('location_id', 'photo_id', name=op.f('pk-location_photo'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_photo')
    # ### end Alembic commands ###
