"""Add Events

Revision ID: 169956911e35
Revises: d14fd711a3a3
Create Date: 2018-05-01 00:30:13.853077

"""
from alembic import op
import sqlalchemy as sa
import hapcat.types


# revision identifiers, used by Alembic.
revision = '169956911e35'
down_revision = 'd14fd711a3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', hapcat.types.GUID(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('location_id', hapcat.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['uuidobject.id'], name=op.f('fk-event-id-uuidobject-id')),
    sa.ForeignKeyConstraint(['location_id'], ['rawlocation.id'], name=op.f('fk-event-location_id-rawlocation-id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-event'))
    )
    op.create_table('event_tag',
    sa.Column('event_id', hapcat.types.GUID(), nullable=False),
    sa.Column('tag_id', hapcat.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk-event_tag-event_id-event-id')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk-event_tag-tag_id-tag-id')),
    sa.PrimaryKeyConstraint('event_id', 'tag_id', name=op.f('pk-event_tag'))
    )
    op.alter_column('location', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_table('event_tag')
    op.drop_table('event')
    # ### end Alembic commands ###
