"""Change event location_id to rawlocation_id

Revision ID: 46b2f715adcd
Revises: 169956911e35
Create Date: 2018-05-01 00:49:56.526266

"""
from alembic import op
import sqlalchemy as sa
import hapcat.types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46b2f715adcd'
down_revision = '169956911e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('rawlocation_id', hapcat.types.GUID(), nullable=False))
    op.drop_constraint('fk-event-location_id-rawlocation-id', 'event', type_='foreignkey')
    op.create_foreign_key(op.f('fk-event-rawlocation_id-rawlocation-id'), 'event', 'rawlocation', ['rawlocation_id'], ['id'])
    op.drop_column('event', 'location_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('location_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk-event-rawlocation_id-rawlocation-id'), 'event', type_='foreignkey')
    op.create_foreign_key('fk-event-location_id-rawlocation-id', 'event', 'rawlocation', ['location_id'], ['id'])
    op.drop_column('event', 'rawlocation_id')
    # ### end Alembic commands ###
