"""Add a vote table

Revision ID: 675a18781b01
Revises: 10b42a21a211
Create Date: 2018-05-01 23:35:27.277218

"""
from alembic import op
import sqlalchemy as sa
import hapcat.types
import sqlalchemy_utils.types


# revision identifiers, used by Alembic.
revision = '675a18781b01'
down_revision = '10b42a21a211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('votable_id', sqlalchemy_utils.types.uuid.UUIDType, nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType, nullable=False),
    sa.Column('numvotes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk-vote-user_id-user-id'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['votable_id'], ['votable.id'], name=op.f('fk-vote-votable_id-votable-id'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('votable_id', 'user_id', name=op.f('pk-vote'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    # ### end Alembic commands ###
