"""Add basic location table information

Revision ID: 708f00bc0d4f
Revises: 093027200eef
Create Date: 2018-04-12 00:34:01.646769

"""
from alembic import op
import sqlalchemy as sa
import hapcat.types


# revision identifiers, used by Alembic.
revision = '708f00bc0d4f'
down_revision = '093027200eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
        sa.Column('id', hapcat.types.GUID(), nullable=False),
        sa.Column('name', sa.UnicodeText(), nullable=True),
        sa.Column('address', sa.UnicodeText(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk-location'))
    )
    op.create_table('location_tag',
        sa.Column('location_id', hapcat.types.GUID(), nullable=False),
        sa.Column('tag_id', hapcat.types.GUID(), nullable=False),
        sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk-location_tag-location_id-location-id')),
        sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk-location_tag-tag_id-tag-id')),
        sa.PrimaryKeyConstraint('location_id', 'tag_id', name=op.f('pk-location_tag'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_tag')
    op.drop_table('location')
    # ### end Alembic commands ###
