"""Index photo URLs

Revision ID: 7541b184f17e
Revises: 675a18781b01
Create Date: 2018-05-02 18:09:16.194237

"""
from alembic import op
import sqlalchemy as sa
import hapcat.types
import sqlalchemy_utils.types


# revision identifiers, used by Alembic.
revision = '7541b184f17e'
down_revision = '675a18781b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix-photo-photo_photourl'), 'photo', ['photourl'], unique=True)
    op.drop_constraint('uq-photo-photourl', 'photo', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq-photo-photourl', 'photo', ['photourl'])
    op.drop_index(op.f('ix-photo-photo_photourl'), table_name='photo')
    # ### end Alembic commands ###
