"""Use sqlalchemy_utils types

Revision ID: 7e3bd4940058
Revises: 46b2f715adcd
Create Date: 2018-05-01 02:12:06.588951

"""
from alembic import op
import sqlalchemy as sa
import hapcat.types
import sqlalchemy_utils.types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e3bd4940058'
down_revision = '46b2f715adcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column(
            'password',
            sqlalchemy_utils.types.PasswordType(
                schemes=[
                    'argon2',
                    'bcrypt',
                ],
                default='argon2',
                deprecated=['auto'],
            ),
        nullable=False,
        )
    )

    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
