"""Cascade foreign key deletes

Revision ID: dd02119e8e12
Revises: 7e3bd4940058
Create Date: 2018-05-01 02:52:24.312869

"""
from alembic import op
import sqlalchemy as sa
import hapcat.types
import sqlalchemy_utils.types


# revision identifiers, used by Alembic.
revision = 'dd02119e8e12'
down_revision = '7e3bd4940058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk-event-rawlocation_id-rawlocation-id', 'event', type_='foreignkey')
    op.drop_constraint('fk-event-id-uuidobject-id', 'event', type_='foreignkey')
    op.create_foreign_key(op.f('fk-event-id-uuidobject-id'), 'event', 'uuidobject', ['id'], ['id'], ondelete='cascade')
    op.create_foreign_key(op.f('fk-event-rawlocation_id-rawlocation-id'), 'event', 'rawlocation', ['rawlocation_id'], ['id'], ondelete='cascade')
    op.drop_constraint('fk-event_tag-event_id-event-id', 'event_tag', type_='foreignkey')
    op.drop_constraint('fk-event_tag-tag_id-tag-id', 'event_tag', type_='foreignkey')
    op.create_foreign_key(op.f('fk-event_tag-tag_id-tag-id'), 'event_tag', 'tag', ['tag_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(op.f('fk-event_tag-event_id-event-id'), 'event_tag', 'event', ['event_id'], ['id'], ondelete='cascade')
    op.drop_constraint('fk-location-id-rawlocation-id', 'location', type_='foreignkey')
    op.create_foreign_key(op.f('fk-location-id-rawlocation-id'), 'location', 'rawlocation', ['id'], ['id'], ondelete='cascade')
    op.drop_constraint('fk-location_tag-location_id-location-id', 'location_tag', type_='foreignkey')
    op.drop_constraint('fk-location_tag-tag_id-tag-id', 'location_tag', type_='foreignkey')
    op.create_foreign_key(op.f('fk-location_tag-tag_id-tag-id'), 'location_tag', 'tag', ['tag_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(op.f('fk-location_tag-location_id-location-id'), 'location_tag', 'location', ['location_id'], ['id'], ondelete='cascade')
    op.drop_constraint('fk-rawlocation-id-uuidobject-id', 'rawlocation', type_='foreignkey')
    op.create_foreign_key(op.f('fk-rawlocation-id-uuidobject-id'), 'rawlocation', 'uuidobject', ['id'], ['id'], ondelete='cascade')
    op.drop_constraint('fk-tag-id-uuidobject-id', 'tag', type_='foreignkey')
    op.create_foreign_key(op.f('fk-tag-id-uuidobject-id'), 'tag', 'uuidobject', ['id'], ['id'], ondelete='cascade')
    op.drop_constraint('fk-user-id-uuidobject-id', 'user', type_='foreignkey')
    op.create_foreign_key(op.f('fk-user-id-uuidobject-id'), 'user', 'uuidobject', ['id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk-user-id-uuidobject-id'), 'user', type_='foreignkey')
    op.create_foreign_key('fk-user-id-uuidobject-id', 'user', 'uuidobject', ['id'], ['id'])
    op.drop_constraint(op.f('fk-tag-id-uuidobject-id'), 'tag', type_='foreignkey')
    op.create_foreign_key('fk-tag-id-uuidobject-id', 'tag', 'uuidobject', ['id'], ['id'])
    op.drop_constraint(op.f('fk-rawlocation-id-uuidobject-id'), 'rawlocation', type_='foreignkey')
    op.create_foreign_key('fk-rawlocation-id-uuidobject-id', 'rawlocation', 'uuidobject', ['id'], ['id'])
    op.drop_constraint(op.f('fk-location_tag-location_id-location-id'), 'location_tag', type_='foreignkey')
    op.drop_constraint(op.f('fk-location_tag-tag_id-tag-id'), 'location_tag', type_='foreignkey')
    op.create_foreign_key('fk-location_tag-tag_id-tag-id', 'location_tag', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key('fk-location_tag-location_id-location-id', 'location_tag', 'location', ['location_id'], ['id'])
    op.drop_constraint(op.f('fk-location-id-rawlocation-id'), 'location', type_='foreignkey')
    op.create_foreign_key('fk-location-id-rawlocation-id', 'location', 'rawlocation', ['id'], ['id'])
    op.drop_constraint(op.f('fk-event_tag-event_id-event-id'), 'event_tag', type_='foreignkey')
    op.drop_constraint(op.f('fk-event_tag-tag_id-tag-id'), 'event_tag', type_='foreignkey')
    op.create_foreign_key('fk-event_tag-tag_id-tag-id', 'event_tag', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key('fk-event_tag-event_id-event-id', 'event_tag', 'event', ['event_id'], ['id'])
    op.drop_constraint(op.f('fk-event-rawlocation_id-rawlocation-id'), 'event', type_='foreignkey')
    op.drop_constraint(op.f('fk-event-id-uuidobject-id'), 'event', type_='foreignkey')
    op.create_foreign_key('fk-event-id-uuidobject-id', 'event', 'uuidobject', ['id'], ['id'])
    op.create_foreign_key('fk-event-rawlocation_id-rawlocation-id', 'event', 'rawlocation', ['rawlocation_id'], ['id'])
    # ### end Alembic commands ###
