"""Use global unique IDs

Revision ID: f008e0185df5
Revises: 789c0115af6c
Create Date: 2018-04-30 19:10:31.492849

"""
from alembic import op
import sqlalchemy as sa
import hapcat.types


# revision identifiers, used by Alembic.
revision = 'f008e0185df5'
down_revision = '789c0115af6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uuidobject',
    sa.Column('id', hapcat.types.GUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk-uuidobject'))
    )
    op.create_foreign_key(op.f('fk-location-id-uuidobject-id'), 'location', 'uuidobject', ['id'], ['id'])
    op.create_foreign_key(op.f('fk-tag-id-uuidobject-id'), 'tag', 'uuidobject', ['id'], ['id'])
    op.add_column('user', sa.Column('id', hapcat.types.GUID(), nullable=False))
    op.create_index(op.f('ix-user-user_username'), 'user', ['username'], unique=True)
    op.create_foreign_key(op.f('fk-user-id-uuidobject-id'), 'user', 'uuidobject', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk-user-id-uuidobject-id'), 'user', type_='foreignkey')
    op.drop_index(op.f('ix-user-user_username'), table_name='user')
    op.drop_column('user', 'id')
    op.drop_constraint(op.f('fk-tag-id-uuidobject-id'), 'tag', type_='foreignkey')
    op.drop_constraint(op.f('fk-location-id-uuidobject-id'), 'location', type_='foreignkey')
    op.drop_table('uuidobject')
    # ### end Alembic commands ###
